<script>
    import "../style.css";

    import { onMount } from "svelte";
    import { fade } from "svelte/transition";
    import { experience } from "/src/store.js";

    let question = 0;
    let start = false;
    let wrong = false;
    let fadeDuration = 150;
    let isVisible = false;
    let minting = false;

    onMount(() => {
        const interval = setInterval(() => { 
            isVisible = !isVisible;
            setTimeout(() => {
                isVisible = !isVisible;
            }, 100);
        }, 5000);

        const store = experience.subscribe(value => {
            minting = value;
        });

            return () => {
                clearInterval(interval);
                // store.unsubscribe();
            }
    });

    const startExperience = () => {
        start = true;
        question = 0;
        experience.set(true);
    }

    const closeExperience = () => {
        start = false;
        question = 0;
        wrong = false;
        experience.set(false);

        console.log("closeExperience");
    }

    $: if (minting) {
        setTimeout(() => {
            startExperience()
        }, "10");
    }
</script>

<div class="h-full w-full relative">
    <!-- BACKGROUND -->

    <div class="absolute right-0 top-0 z-10">
        <a on:click={ closeExperience } href={"#"}><img loading="lazy" src="/minting/exit.png" alt="exit"></a>
    </div>

    <!-- Image Map Generated by http://www.image-map.net/ -->

    <div class="">
        <!-- <img class="select-none mx-auto h-full" src="/minting/minting-background.png" alt=""> -->

    {#if start}
        
        <!-- ADOPT FORM -->
      {#if question < 1}
            <img class="select-none mx-auto xl:w-2/3" src="/minting/adopt-koki.png" alt="">
            <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex items-center justify-center flex-col w-1/2 h-1/2 xl:w-96 xl:h-96 gap-2 xl:gap-6 m-auto font-century uppercase tracking-[0.3em]">
                <h1 class="text-lg xl:text-5xl text-center">adopti ami<br/>koki</h1>
                <img class="absolute w-10 h-10 xl:w-fit xl:h-fit right-5 xl:right-0 top-5 xl:top-10" src="/minting/heart.png" alt="heart">
                <div class="text-xs xl:text-3xl bg-white p-1 xl:p-3 flex w-full justify-between border-black border-[1px] shadow-xl shadow-pink-500">
                    <label for="amount">Amounti</label>
                    <input class="w-10 xl:w-32 text-right" type="text" id="amount" name="amount">
                </div>
                <div class="text-xs xl:text-3xl bg-white p-1 xl:p-3 flex w-full justify-between border-black border-[1px] shadow-xl shadow-pink-500">
                    <label for="total flex-grow">Totali</label>
                    <p class="text-right">10 ETH</p>
                </div>

                <button on:click={()=>{question++}} class="w-32 h-32 xl:w-72 xl:h-12" type="submit"><img class="w-full" src="/minting/adopt-button.png" alt=""></button>
            </div>

        {:else}
            <img loading="lazy" in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration }} class="w-full object-cover" src="/minting/minting-background.png" alt="Q1 background">
        {/if}
            
        <!-- BLINKING -->
        {#if isVisible & question > 0}
            <a class="" href={"#"}><img loading="lazy" class="absolute left-1/2 -translate-x-1/2 top-0 h-fit w-full object-cover" src="/minting/minting-eyes.png" alt="Minting Eyes"></a>
        {/if}
    
    {:else}
        <a on:click={startExperience} href={"#"}><img class="h-full w-fit object-cover mx-auto" src="/minting/psipsikoko-minting.png" alt="Minting"></a>
    {/if}

    <!-- QUESTION 1 -->                
    {#if question == 1}

        <svg in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration }} class="absolute left-1/2 -translate-x-1/2 top-0 w-full object-cover" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2436 1419">
            <image width="2436" height="1419" href="/minting/minting-01.png"></image> 
            <a on:click={()=> { question++ }} href={"#"}>
            <rect x="1478" y="650" fill="#fff" opacity="0" width="636" height="90"></rect>
            </a>
            <a on:click={()=> { question++ }} href={"#"}>
            <rect x="1450" y="816" fill="#fff" opacity="0" width="700" height="82"></rect>
            </a>
            <a on:click={()=> { question++ }} href={"#"}>
            <rect x="1568" y="972" fill="#fff" opacity="0" width="430" height="92"></rect>
            </a>
        </svg>
    {/if}

    <!-- QUESTION 2 -->
    {#if question == 2}
        <img loading="lazy" in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration }} class="absolute left-1/2 -translate-x-1/2 top-0 h-full w-full" src="/minting/minting-smile1.png" alt="Q1 background">

        <svg in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration }} class="absolute left-1/2 -translate-x-1/2 top-0 h-full w-full" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2436 1419">
            <image width="2436" height="1419" href="/minting/minting-02.png"></image> 
            <a on:click={()=> { question++ }} href={"#"}>
                <rect x="1450" y="648" fill="#fff" opacity="0" width="684" height="94"></rect>
            </a>
            <a on:click={()=> { question++ }} href={"#"}>
                <rect x="1430" y="816" fill="#fff" opacity="0" width="728" height="82"></rect>
            </a>
            <a on:click={()=> { question++ }} href={"#"}>
                <rect x="1452" y="972" fill="#fff" opacity="0" width="690" height="92"></rect>
            </a>
        </svg>
    {/if}

    <!-- QUESTION 3 -->
    {#if question == 3}
        <img loading="lazy" in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration }} class="absolute left-1/2 -translate-x-1/2 top-0 h-full w-full" src="/minting/minting-smile2.png" alt="Q1 background">
        <svg in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration }} class="absolute left-1/2 -translate-x-1/2 top-0 h-full w-full" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2436 1419">
            <image width="2436" height="1419" href="/minting/minting-03.png"></image> 
            <a on:click={()=> { wrong = true }} href={"#"}>
            <rect x="1694" y="640" fill="#fff" opacity="0" width="212" height="82"></rect>
            </a>
            <a on:click={()=> { wrong = true }} href={"#"}>
            <rect x="1554" y="812" fill="#fff" opacity="0" width="476" height="82"></rect>
            </a>
            <a on:click={()=> { wrong = true }} href={"#"}>
            <rect x="1466" y="968" fill="#fff" opacity="0" width="694" height="92"></rect>
            </a>
        </svg>
    {/if}

    <!-- WRONG -->
    {#if wrong }
        <img loading="lazy" in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration } } class="absolute left-1/2 -translate-x-1/2 top-0 h-full w-full" src="/minting/minting-wrong.png" alt="Q1 background">
        <img loading="lazy" in:fade={{ duration: fadeDuration }} out:fade={{ duration: fadeDuration }} class="absolute left-1/2 -translate-x-1/2 top-0 h-full w-full" src="/minting/minting-sad1.png" alt="Q1 background">
    {/if}
    </div>
</div>

<style>
    h1 {
        /* Prefix required. Even Firefox only supports the -webkit- prefix */
        -webkit-text-stroke-width: 1px;
        -webkit-text-stroke-color: white;
        text-shadow: 1px 1px 8px #e76491;
        }
</style>